### ISSUE TITLE
Stacks changed formats

### ISSUE THREAD

**Issue by RobertBakaric** [lyl8086/RADscripts#1]
Hi, 

I noticed stacks 2.0 changed output formats so whenever scripts are used they do not produced a desired output. Problems are with sorting  and assembly. Would it be too much of a problem to adapt  the existing scripts? 

Cheers

**Comment by lyl8086** [comment]
Hi, @RobertBakaric 

I have fixed this issue in the latest 1.01 version of RADassembler, please download and re-install it at https://github.com/lyl8086/RADscripts/releases/download/V1.01/RADassembler.tar.gz.

Any bugs please contact me.

Best,
Yulong
